name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build the Docker image
      run: |
        IMAGE_TAG=$(date +%Y%m%d%H%M%S)  # Use a stricter format for the tag
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV  # Export the IMAGE_TAG to be accessible in other jobs
        echo "Building Docker image with tag: $IMAGE_TAG"
        docker build . --file Dockerfile --tag my-image-name:$IMAGE_TAG

  test:
    runs-on: ubuntu-latest
    needs: build  # Ensure this job runs only after the build job completes

    steps:
    - uses: actions/checkout@v4

    - name: Load Docker image tag
      run: echo "IMAGE_TAG=${{ env.IMAGE_TAG }}"  # Debug to verify the tag is loaded correctly

    - name: Run tests on Docker image
      run: |
        echo "Running tests on Docker image with tag: ${{ env.IMAGE_TAG }}"
        docker run --rm my-image-name:${{ env.IMAGE_TAG }} pytest tests/
