name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build the Docker image
      run: |
        IMAGE_TAG=$(date +%Y%m%d%H%M%S)  # Use a stricter format for the tag
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
        echo "Building Docker image with tag: $IMAGE_TAG"
        docker build . --file Dockerfile --tag my-image-name:$IMAGE_TAG

  
        

  
